### PR TITLE
add 10.x.x LTS reference in docs

### PR DESCRIPTION
**Pull request by movebits**
JIRA - [ALI-21302](https://coppercrm.atlassian.net/browse/ALI-21302)

Add recommended Node version 10.x.x LTS version to docs.

### CODE REVIEW

**Comment by katiemhuang** [comment]
@movebits is there another PR with the change for the Jira (updating counter -> count)?

I might be missing something

**Comment by brigham-hausman** [comment]
@katiemhuang The requested change was made quite some time ago, but never got published.
https://github.com/ProsperWorks/copper-sdk/commit/c3c51e1ea6816d658dbcf5bcf4c00ec00cd97fe2

**Comment by katiemhuang** [comment]
ah got it! thanks @brigham-hausman

**Comment by fzhang0111** [comment]
The repository is not in the right state

**Comment by fzhang0111** [comment]
@brigham-hausman I will reopen it once make it integrating with TravisCI. (all of other repo. can be, just not this one at this moment)

**Comment by brigham-hausman** [comment]
👍 Thanks @fzhang0111 ! You rock!!

**Pull request closed without merging**
